# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "sagarpatke/centos8"

  config.vm.define :node1 do |n|
    n.vm.provision :ansible, run: 'always' do |ansible|
      ansible.playbook = 'test.yml'
    end

    n.vm.network :private_network, ip: '192.168.100.12', __virtualbox_intnet: 'net1'
  end

  config.vm.define :node2 do |n|
    n.vm.network :private_network, ip: '192.168.100.81', __virtualbox_intnet: 'net1'
  end
end
